import { Command } from '../cli/command.js';

class GenerateCommand extends Command {
  name = 'generate <description>';
  description = 'Synthesize a high-fidelity Figma UI from a description using MoE agent pipeline';
  needsConnection = true;

  constructor() {
    super();
    this.options = [
      { flags: '-v, --verbose', description: 'Show full MoE pipeline trace' },
      { flags: '--mode <mode>', description: 'Theme mode: Light or Dark', defaultValue: 'Light' },
      { flags: '--dry-run', description: 'Show pipeline results without rendering' }
    ];
  }

  async execute(ctx, options, description) {
    ctx.logSuccess(`Synthesizing UI for: "${description}"...`);

    try {
      // ── MoE Pipeline ──────────────────────────────
      const { orchestrator } = await ctx.getAgents();

      const pipelineResult = await orchestrator.execute(ctx, description, {
        mode: options.mode,
      });

      if (options.verbose) {
        orchestrator.printTrace();
      }

      if (!pipelineResult.success) {
        ctx.logError('MoE pipeline failed:');
        for (const [name, result] of Object.entries(pipelineResult.results || {})) {
          if (result.errors && result.errors.length > 0) {
            result.errors.forEach(e => ctx.logError(`  [${name}] ${e}`));
          }
        }
        return;
      }

      // ── Extract Results ───────────────────────────

      const builderResult = pipelineResult.results?.builder;
      const guardianResult = pipelineResult.results?.guardian;
      const a11yResult = pipelineResult.results?.a11y;

      // Show Guardian validation report
      if (guardianResult?.data?.report) {
        const report = guardianResult.data.report;
        if (report.violations.length > 0) {
          ctx.logWarning(`Guardian: ${report.stats.warnings} warnings, ${report.stats.errors} errors, ${report.stats.info} info`);
          if (options.verbose) {
            report.violations.forEach(v => {
              const icon = v.severity === 'error' ? '❌' : v.severity === 'warning' ? '⚠️' : 'ℹ️';
              console.log(`  ${icon} [${v.ruleId}] ${v.nodeName}: ${v.message}`);
            });
          }
        } else {
          ctx.logSuccess('Guardian: All rules passed ✓');
        }
      }

      // Show A11y report
      if (a11yResult?.data?.a11y) {
        const a11y = a11yResult.data.a11y;
        if (a11y.pass) {
          ctx.logSuccess(`A11y: Score ${a11y.score}/100 ✓`);
        } else {
          ctx.logWarning(`A11y: Score ${a11y.score}/100 — ${a11y.issues.length} issues`);
        }
      }

      // ── Render ────────────────────────────────────

      const jsx = pipelineResult.pipelineData?.jsx || builderResult?.data?.jsx;

      if (!jsx) {
        ctx.logError('No JSX generated by the pipeline');
        return;
      }

      if (options.verbose) {
        console.log('\n--- Synthesized JSX ---');
        console.log(jsx.trim());
        console.log('------------------------\n');
      }

      if (options.dryRun) {
        ctx.logSuccess('Dry-run complete. Pipeline finished without rendering.');
        return;
      }

      const result = await ctx.render(jsx);
      if (result && result.error) {
        ctx.logError(`Render failed: ${result.error}`);
      } else {
        const templateUsed = builderResult?.data?.templateUsed;
        ctx.logSuccess(`UI rendered successfully${templateUsed ? ` (template: ${templateUsed})` : ''} — ${pipelineResult.duration}ms`);
      }
    } catch (err) {
      ctx.logError(`Generation error: ${err.message}`);
    }
  }
}

export default new GenerateCommand();
