import { Command } from '../../cli/command.js';
import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';
import inquirer from 'inquirer';
import { saveWorkflow, WORKFLOW_PATH } from '../../utils/design-workflow.js';

class DesignStartCommand extends Command {
  name = 'design start';
  description = 'Run the Design Wizard [ALFA]';
  needsConnection = false;

  async execute(ctx) {
    ctx.log(chalk.yellow('[ALFA]') + ' Starting the Design Wizard...');

    const answers = await inquirer.prompt([
      {
        type: 'input',
        name: 'projectName',
        message: 'Enter the Project Name:',
        validate: input => input.trim().length > 0 || 'Project name cannot be empty.'
      },
      {
        type: 'list',
        name: 'productType',
        message: 'What are you building?',
        choices: [
          'Mobile App',
          'Web App',
          'Dashboard',
          'Admin Panel',
          'SaaS Landing Page',
          'Other'
        ]
      },
      {
        type: 'input',
        name: 'goal',
        message: 'What is the primary goal of this product?',
        validate: input => input.length > 10 || 'Please provide a more detailed goal.'
      },
      {
        type: 'input',
        name: 'audience',
        message: 'Who is the target audience?',
        default: 'General Users'
      },
      {
        type: 'checkbox',
        name: 'platforms',
        message: 'Target platforms?',
        choices: ['iOS', 'Android', 'Web (Desktop)', 'Web (Mobile)'],
        default: ['Web (Desktop)']
      },
      {
        type: 'checkbox',
        name: 'features',
        message: 'Select key features:',
        choices: [
          'User Authentication',
          'Data Visualization/Charts',
          'Real-time Messaging',
          'E-commerce/Payments',
          'Content Management',
          'API Integration',
          'Push Notifications'
        ]
      },
      {
        type: 'list',
        name: 'aesthetic',
        message: 'Choose a primary aesthetic direction:',
        choices: [
          'Modern & Minimalist',
          'Professional & Corporate',
          'Playful & Bold',
          'Dark & High-Tech'
        ]
      }
    ]);

    const projectDir = join(process.cwd(), answers.projectName.toLowerCase().replace(/\s+/g, '-'));
    
    try {
      // 1. Create folders
      mkdirSync(projectDir, { recursive: true });
      mkdirSync(join(projectDir, 'research'), { recursive: true });
      mkdirSync(join(projectDir, 'wireframes'), { recursive: true });
      mkdirSync(join(projectDir, 'ui'), { recursive: true });
      mkdirSync(join(projectDir, 'reports'), { recursive: true });

      // 2. Generate Product Brief
      const briefContent = `# Product Brief: ${answers.projectName}

## Overview
- **Product Type:** ${answers.productType}
- **Goal:** ${answers.goal}
- **Target Audience:** ${answers.audience}

## Platforms
${answers.platforms.map(p => `- ${p}`).join('\n')}

## Key Features
${answers.features.map(f => `- ${f}`).join('\n')}

## Aesthetic Direction
- **Style:** ${answers.aesthetic}

---
*Generated by figma-gemini-cli Design Wizard on ${new Date().toLocaleDateString()}*
`;

      writeFileSync(join(projectDir, 'research', 'product-brief.md'), briefContent);
      const workflow = {
        stage: 'Architecture',
        timestamp: new Date().toISOString(),
        projectName: answers.projectName,
        projectDir,
        discovery: answers,
      };
      saveWorkflow(workflow);

      const payload = {
        success: true,
        projectName: answers.projectName,
        projectDir,
        workflowPath: WORKFLOW_PATH,
        stage: 'Architecture',
        discovery: answers,
        generated: {
          directories: ['research', 'wireframes', 'ui', 'reports'],
          files: [join(projectDir, 'research', 'product-brief.md')],
        },
        nextSteps: [
          'Open research/product-brief.md to review your requirements.',
          'Run `design architecture` to define the product structure.',
        ],
      };

      if (ctx.isJson) {
        ctx.logSuccess(`Project '${answers.projectName}' scaffolded successfully!`, payload);
      } else {
        ctx.logSuccess(`\nProject '${answers.projectName}' scaffolded successfully!`);
        console.log(chalk.cyan('\nGenerated Structure:'));
        console.log(chalk.white(`  ${answers.projectName}/`));
        console.log(chalk.gray(`  ├── research/`));
        console.log(chalk.blue(`  │   └── product-brief.md`));
        console.log(chalk.gray(`  ├── wireframes/`));
        console.log(chalk.gray(`  ├── ui/`));
        console.log(chalk.gray(`  └── reports/`));
        
        console.log(chalk.green(`\nNext Steps: Open 'research/product-brief.md' to review your requirements, then run 'design architecture'.\n`));
      }

    } catch (err) {
      ctx.logError(`Failed to scaffold project: ${err.message}`);
    }
  }
}

export default new DesignStartCommand();
